name: Release and Install App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Release and Install App
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Authenticate
        uses: vtex/action-toolbelt@v8
        with:
          account: vtextitantools
          appKey: ${{ secrets.VTEX_TOOLBELT_KEY }}
          appToken: ${{ secrets.VTEX_TOOLBELT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Release App
        run: vtex release patch stable

      - name: Install App
        run: vtex install
